### ISSUE TITLE
Right hand cursor text prompts persist and accumalate

### ISSUE THREAD

**Issue by 0beron** [brandonmousseau/vhvr-mod#106] opened 2021-07-13 20:58 UTC
After version 0.6, the right hand motion controller cursor has text prompts that don't clear, for example:
'Something to use [E]'
or
'Cooking Station [1-8] Cook item'
These can stack on top of each other and remain throughout a play session.

The left hand seems to be working correctly, playing on Valve Index.

Edit: on a subsequent play session, it did not reoccur. It was observed on the same session as issue #107

**Comment by brandonmousseau** [comment] 2021-07-25 20:14
I'm going to close this issue for now as we can't reproduce - feel free to re-open if you see it again and adding as much as detail as possible would be very helpful.

**Closed by brandonmousseau** 2021-07-25 20:14 UTC
