### ISSUE TITLE
Mouse cursor dissapears when playing flatscreen mode VHVR

### ISSUE THREAD

**Issue by catweazelFFFF** [brandonmousseau/vhvr-mod#354] opened 2023-09-23 12:17 UTC
When using the mod on a flatscreen with unmodded Valheim upon opening the inventory with tab key the mouse cursor turn in to a 1px white dot. It stays that way until game reboot. When hitting ESC before hitting TAB key the cursor is unaffected.
![Mouse bug Valheim VHVR flatscreen mode](https://github.com/brandonmousseau/vhvr-mod/assets/145844246/2c657868-cd24-40c2-a82a-bbd93c6f73ce)
![Mouse bug Valheim VHVR flatscreen mode2](https://github.com/brandonmousseau/vhvr-mod/assets/145844246/87529716-07f4-408c-902e-e574f7d2d643)

I have highlighted the bugged mouse cursor in the screenshots

**Comment by brandonmousseau** [comment] 2023-09-23 18:02
Thanks, I've had this issue reported in our discord too and am having some
people test out a fix currently so hopefully will have this resolved soon.

**Comment by catweazelFFFF** [comment] 2023-09-24 09:19
Thank you very much, your tireless efforts are most appreciated! Will leave this issue open for the time being.

**Comment by eviltek2099** [comment] 2024-05-04 15:19
any update on this yet? I just tried it and still no Mouse cursor on flatscreen mode

**Comment by brandonmousseau** [comment] 2024-05-04 15:42
This had long been fixed but forgot to close the issue. The problem you are seeing now is new and caused by recent game updates. We are working on getting a new version of the mod, will most likely happen after Ashland update goes live.

**Closed by brandonmousseau** 2024-05-04 15:42 UTC
